#!/bin/bash 



display_usage()
{
echo usage:$0 '[rfald peer address] [Ethernet inetface name]'
echo Example:$0 10.1.250.228 eth0 
}


if [ -z "$1" ] || [ -z "$2" ];then 
	echo missing argument 
        display_usage
	exit 1
fi



modprobe mac80211
modprobe mac80211_hwsim 

echo loadong mac80211 and mac80211_hwsim module

ethIP=$(ifconfig $2 |grep -oP 'inet \K\S+')
if [ -z "$(pgrep vUE-rfald)" ]; then
	echo Running vUE-rfald
	vUE-rfald-multi -i $ethIP -d $1 -m >>/dev/null 2>&1 &
else
	echo Fail to run vUE-rfald, process exists
fi 	

if [ -n "$(pgrep wpa_supplicant)" ];then 
	echo Cleanning exist wpa_supplicant
	kill -9 $(pgrep wpa_supplicant)
fi

ethNetmask=$(ifconfig $2 |grep -oP 'netmask \K\S+')
IFS=. read -r io1 io2 io3 io4 <<< $ethIP
IFS=. read -r mo1 mo2 mo3 mo4 <<< $ethNetmask
network="$((io1 & mo1)).$(($io2 & mo2)).$((io3 & mo3)).$((io4 & mo4))"

echo adding routing rule: net $network netmask $ethNetmask dev $2
route add -net $network netmask $ethNetmask dev $2 >>/dev/null 2>&1

       	
exit 0
